### ISSUE TITLE
Periods doubled after section headings

### ISSUE THREAD

**Issue by ParadaCarleton** [Marmare314/lemmify#12]
When section headings end in a period (e.g. "1.2."), the period in each definition is doubled. For example:
![image](https://github.com/Marmare314/lemmify/assets/71727937/427e938a-2b48-4796-9087-59ba0a540136)

**Comment by Marmare314** [comment]
This seems like a common enough numbering style to be considered in the default `thm-numbering-style`. Otherwise a custom numbering style can always be provided. Thanks for reporting this!
