### ISSUE TITLE
Definition not working

### ISSUE THREAD

**Issue by porcaror** [Marmare314/lemmify#18]
Hi. I'm trying to use a definion as:

#definition(name: "Elemento invertibile")[Dato un insieme numerico $A$ (con $A = ZZ$ o  $A = QQ$ o  $A = RR$ o $A = CC$), si dice che un elemento $x in A$, con $x eq.not 0$ è invertibile (o anche che è una _unità_) se $exists y in A$ tale che $x y = y x = 1$. Tale elemento  $y$ si denota con  $x^(-1)$ e si dice inverso di $x$.]

but I have the following error message: irriducibilita.typ|120 col 1| error: unknown variable: definition

I tried to add definition also to 
#let (
  theorem, lemma, corollary,
  remark, proposition, example,
proof, rules, definition: thm-rules
) = default-theorems("thm-group", lang: "it")
#show: thm-rules

but it didn't work. Can you help me?

**Comment by Marmare314** [comment]
I think the problem is `definition: thm-rules`, which takes the definition key and assigns it to `thm-rules`. It should probably be this instead:
```typ
#let (
theorem, lemma, corollary,
remark, proposition, example,
proof, definition, rules: thm-rules
) = default-theorems("thm-group", lang: "it")
#show: thm-rules
```

**Comment by porcaror** [comment]
Yes great, It works.
Maybe in the next version you could write it in the right place in the example.
Thanks a lot.
Roberto
