### ISSUE TITLE
Numbering appended to name?

### ISSUE THREAD

**Issue by ParadaCarleton** [Marmare314/lemmify#9]
```typst
#let (
  theorem, lemma, corollary,
  remark, proposition, example,
  proof, definition, rules: thm-rules
) = default-theorems("thm-group", lang: "en")
#show: thm-rules
#theorem(name: "Some theorem")[
  Theorem content goes here.
]<thm>
```
This example from the tutorial generates this:
![image](https://github.com/Marmare314/lemmify/assets/71727937/3542a9b9-910c-4bf1-9a8e-20043fdbcc52)

For some reason, the theorem's number is being appended to its name, causing it to appear twice.

**Comment by Marmare314** [comment]
What version of typst are you using? I suspect that something about figures was changed in the latest release.

**Comment by ParadaCarleton** [comment]
> What version of typst are you using? I suspect that something about figures was changed in the latest release.

Most recent version (on the web app).

**Comment by donRumata03** [comment]
I've encountered the same issue with typst of version: `typst 0.8.0 (360cc9b9)`
